version: '3'
services:
  server:
    image: hex-chess-app
    environment:
      - PORT=3000
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=3000
    ports:
      - "3000:3000"